config/routes.rb
Gw2AwesomeBuilder::Application.routes.draw do
  resources :weapons

  resources :jewelries

  resources :suits

  resources :trinkets do
    get 'page/:page', :action => :index, :on => :collection
  end

  resources :outfits do
    get 'page/:page', :action => :index, :on => :collection
  end

  resources :armors do
    get 'page/:page', :action => :index, :on => :collection
  end

  resources :enhancements do
    get 'page/:page', :action => :index, :on => :collection
  end

  resources :statistics do
    get 'page/:page', :action => :index, :on => :collection
  end

  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/statistic.rb
class Statistic < ActiveRecord::Base
  resourcify
  attr_accessible :name

  has_many :enhancements

  validates :name,
    presence: true,
    uniqueness: true,
    length: { maximum: 36 }
end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  # GET /statistics
  # GET /statistics.json
  def index
    @statistics = Statistic.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @statistics }
    end
  end

  # GET /statistics/1
  # GET /statistics/1.json
  def show
    @statistic = Statistic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @statistic }
    end
  end

  # GET /statistics/new
  # GET /statistics/new.json
  def new
    @statistic = Statistic.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @statistic }
    end
  end

  # GET /statistics/1/edit
  def edit
    @statistic = Statistic.find(params[:id])
  end

  # POST /statistics
  # POST /statistics.json
  def create
    @statistic = Statistic.new(params[:statistic])

    respond_to do |format|
      if @statistic.save
        format.html { redirect_to @statistic, notice: 'Statistic was successfully created.' }
        format.json { render json: @statistic, status: :created, location: @statistic }
      else
        format.html { render action: "new" }
        format.json { render json: @statistic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /statistics/1
  # PUT /statistics/1.json
  def update
    @statistic = Statistic.find(params[:id])

    respond_to do |format|
      if @statistic.update_attributes(params[:statistic])
        format.html { redirect_to @statistic, notice: 'Statistic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @statistic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statistics/1
  # DELETE /statistics/1.json
  def destroy
    @statistic = Statistic.find(params[:id])
    @statistic.destroy

    respond_to do |format|
      format.html { redirect_to statistics_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/views/statistics/_form.html.haml
= form_for @statistic do |f|
  - if @statistic.errors.any?
    #error_explanation
      %h2= "#{pluralize(@statistic.errors.count, "error")} prohibited this statistic from being saved:"
      %ul
        - @statistic.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :kind
    = f.text_field :kind
  .field
    = f.label :minimum
    = f.text_field :minimum
  .field
    = f.label :maximum
    = f.text_field :maximum
  .field
    = f.label :interval
    = f.text_field :interval
  .actions
    = f.submit 'Save'

app/views/statistics/edit.html.haml
%h1 Editing statistic

= render 'form'

= link_to 'Show', @statistic
\|
= link_to 'Back', statistics_path

app/views/statistics/index.html.haml
%h1 Listing statistics

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @statistics.each do |statistic|
    %tr
      %td= statistic.name
      %td= link_to 'Show', statistic
      %td= link_to 'Edit', edit_statistic_path(statistic)
      %td= link_to 'Destroy', statistic, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Statistic', new_statistic_path

app/views/statistics/new.html.haml
%h1 New statistic

= render 'form'

= link_to 'Back', statistics_path

app/views/statistics/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @statistic.name
%p
  %b Kind:
  = @statistic.kind
%p
  %b Minimum:
  = @statistic.minimum
%p
  %b Maximum:
  = @statistic.maximum
%p
  %b Interval:
  = @statistic.interval

= link_to 'Edit', edit_statistic_path(@statistic)
\|
= link_to 'Back', statistics_path