config/routes.rb
Gw2AwesomeBuilder::Application.routes.draw do
  resources :weapons

  resources :jewelries

  resources :suits

  resources :trinkets do
    get 'page/:page', :action => :index, :on => :collection
  end

  resources :outfits do
    get 'page/:page', :action => :index, :on => :collection
  end

  resources :armors do
    get 'page/:page', :action => :index, :on => :collection
  end

  resources :enhancements do
    get 'page/:page', :action => :index, :on => :collection
  end

  resources :statistics do
    get 'page/:page', :action => :index, :on => :collection
  end

  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/suit.rb
class Suit < ActiveRecord::Base
  resourcify
  before_save :generate_statistics

  # Associations
  belongs_to :weight

  has_many :outfits
  has_and_belongs_to_many :armors

  # Validations
  validates_presence_of :armors
  # validates_associated :armors

  # Scopes
  scope :light, where(weight_id: WeightModule::WEIGHT[:light][:id])
  scope :medium, where(weight_id: WeightModule::WEIGHT[:medium][:id])
  scope :heavy, where(weight_id: WeightModule::WEIGHT[:heavy][:id])

  # Methods
  def generate_statistics
    StatisticModule::statistics.each do |statistic|
      # Set the statistic to 0 before we recalculate
      write_attribute(statistic, 0)

      armors.each do |armor|
        write_attribute(statistic, read_attribute(statistic) + armor[statistic])
      end
    end
  end

  # Overridden Methods
  def ==(other)
    return false unless self.weight_id == other.weight_id

    StatisticModule::statistics.each do |statistic|
      return false unless read_attribute(statistic) == other[statistic]
    end

    return true
  end
  alias :eql? :==
end

app/controllers/suits_controller.rb
class SuitsController < ApplicationController
  include SortModule
  include ChildExtractionModule

  # GET /suits
  # GET /suits.json
  def index
    @sort ||= 'attack_power desc'
    @suits = Suit.order(@sort).page(params[:page])

    respond_with @suits
  end

  # GET /suits/1
  # GET /suits/1.json
  def show
    @suit = Suit.includes(:armors).find(params[:id])

    respond_with @suit
  end

  # GET /suits/new
  # GET /suits/new.json
  def new
    @suit = Suit.new

    respond_with @suit
  end

  # GET /suits/1/edit
  def edit
    @suit = Suit.find(params[:id])

    respond_with @suit
  end

  # POST /suits
  # POST /suits.json
  def create
    params_armors = params[:suit].delete(:armors)
    @suit = Suit.create(params[:suit]) do |suit|
      hydrate_children!(suit, params_armors, :armors, Armor)
    end

    respond_with @suit
  end

  # PUT /suits/1
  # PUT /suits/1.json
  def update
    @suit = Suit.find(params[:id])

    params_armors = params[:suit].delete(:armors)
    hydrate_children!(@suit, params_armors, :armors, Armor)

    @suit.update_attributes(params[:suit])

    respond_with @suit
  end

  # DELETE /suits/1
  # DELETE /suits/1.json
  def destroy
    @suit = Suit.destroy(params[:id])

    respond_with @suit
  end
end

app/helpers/suits_helper.rb
module SuitsHelper
end

app/views/suits/_form.html.haml
= form_for @suit do |f|
  - if @suit.errors.any?
    #error_explanation
      %h2= "#{pluralize(@suit.errors.count, "error")} prohibited this suit from being saved:"
      %ul
        - @suit.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :armor
    = f.number_field :armor
  .field
    = f.label :hit_points
    = f.number_field :hit_points
  .field
    = f.label :attack_power
    = f.number_field :attack_power
  .field
    = f.label :critical_damage
    = f.number_field :critical_damage
  .field
    = f.label :critical_chance
    = f.number_field :critical_chance
  .field
    = f.label :condition_damage
    = f.number_field :condition_damage
  .field
    = f.label :condition_duration
    = f.number_field :condition_duration
  .field
    = f.label :healing_power
    = f.number_field :healing_power
  .field
    = f.label :boon_duration
    = f.number_field :boon_duration
  .field
    = f.label :magic_find
    = f.number_field :magic_find
  .actions
    = f.submit 'Save'

app/views/suits/edit.html.haml
%h1 Editing suit

= render 'form'

= link_to 'Show', @suit
\|
= link_to 'Back', suits_path

app/views/suits/index.html.haml
%h1 Listing suits

%table
  %tr
    %th Armor
    %th Hit points
    %th Attack power
    %th Critical damage
    %th Critical chance
    %th Condition damage
    %th Condition duration
    %th Healing power
    %th Boon duration
    %th Magic find
    %th
    %th
    %th

  - @suits.each do |suit|
    %tr
      %td= suit.armor
      %td= suit.hit_points
      %td= suit.attack_power
      %td= suit.critical_damage
      %td= suit.critical_chance
      %td= suit.condition_damage
      %td= suit.condition_duration
      %td= suit.healing_power
      %td= suit.boon_duration
      %td= suit.magic_find
      %td= link_to 'Show', suit
      %td= link_to 'Edit', edit_suit_path(suit)
      %td= link_to 'Destroy', suit, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Suit', new_suit_path

app/views/suits/new.html.haml
%h1 New suit

= render 'form'

= link_to 'Back', suits_path

app/views/suits/show.html.haml
%p#notice= notice

%p
  %b Armor:
  = @suit.armor
%p
  %b Hit points:
  = @suit.hit_points
%p
  %b Attack power:
  = @suit.attack_power
%p
  %b Critical damage:
  = @suit.critical_damage
%p
  %b Critical chance:
  = @suit.critical_chance
%p
  %b Condition damage:
  = @suit.condition_damage
%p
  %b Condition duration:
  = @suit.condition_duration
%p
  %b Healing power:
  = @suit.healing_power
%p
  %b Boon duration:
  = @suit.boon_duration
%p
  %b Magic find:
  = @suit.magic_find

= link_to 'Edit', edit_suit_path(@suit)
\|
= link_to 'Back', suits_path