config/routes.rb
Gw2AwesomeBuilder::Application.routes.draw do
  resources :weapons

  resources :jewelries

  resources :suits

  resources :trinkets do
    get 'page/:page', :action => :index, :on => :collection
  end

  resources :outfits do
    get 'page/:page', :action => :index, :on => :collection
  end

  resources :armors do
    get 'page/:page', :action => :index, :on => :collection
  end

  resources :enhancements do
    get 'page/:page', :action => :index, :on => :collection
  end

  resources :statistics do
    get 'page/:page', :action => :index, :on => :collection
  end

  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/weapon.rb
class Weapon < ActiveRecord::Base
  belongs_to :slot
  attr_accessible :armor, :attack_power, :boon_duration, :condition_damage, :condition_duration, :critical_chance, :critical_damage, :gw2db_url, :healing_power, :hit_points, :icon_url, :level, :magic_find, :name
end

app/controllers/weapons_controller.rb
class WeaponsController < ApplicationController
  # GET /weapons
  # GET /weapons.json
  def index
    @weapons = Weapon.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @weapons }
    end
  end

  # GET /weapons/1
  # GET /weapons/1.json
  def show
    @weapon = Weapon.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @weapon }
    end
  end

  # GET /weapons/new
  # GET /weapons/new.json
  def new
    @weapon = Weapon.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @weapon }
    end
  end

  # GET /weapons/1/edit
  def edit
    @weapon = Weapon.find(params[:id])
  end

  # POST /weapons
  # POST /weapons.json
  def create
    @weapon = Weapon.new(params[:weapon])

    respond_to do |format|
      if @weapon.save
        format.html { redirect_to @weapon, notice: 'Weapon was successfully created.' }
        format.json { render json: @weapon, status: :created, location: @weapon }
      else
        format.html { render action: "new" }
        format.json { render json: @weapon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /weapons/1
  # PUT /weapons/1.json
  def update
    @weapon = Weapon.find(params[:id])

    respond_to do |format|
      if @weapon.update_attributes(params[:weapon])
        format.html { redirect_to @weapon, notice: 'Weapon was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @weapon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weapons/1
  # DELETE /weapons/1.json
  def destroy
    @weapon = Weapon.find(params[:id])
    @weapon.destroy

    respond_to do |format|
      format.html { redirect_to weapons_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/weapons_helper.rb
module WeaponsHelper
end

app/views/weapons/_form.html.haml
= form_for @weapon do |f|
  - if @weapon.errors.any?
    #error_explanation
      %h2= "#{pluralize(@weapon.errors.count, "error")} prohibited this weapon from being saved:"
      %ul
        - @weapon.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :level
    = f.number_field :level
  .field
    = f.label :armor
    = f.number_field :armor
  .field
    = f.label :hit_points
    = f.number_field :hit_points
  .field
    = f.label :attack_power
    = f.number_field :attack_power
  .field
    = f.label :critical_damage
    = f.number_field :critical_damage
  .field
    = f.label :critical_chance
    = f.number_field :critical_chance
  .field
    = f.label :condition_damage
    = f.number_field :condition_damage
  .field
    = f.label :condition_duration
    = f.number_field :condition_duration
  .field
    = f.label :healing_power
    = f.number_field :healing_power
  .field
    = f.label :boon_duration
    = f.number_field :boon_duration
  .field
    = f.label :magic_find
    = f.number_field :magic_find
  .field
    = f.label :slot
    = f.text_field :slot
  .field
    = f.label :gw2db_url
    = f.text_field :gw2db_url
  .field
    = f.label :icon_url
    = f.text_field :icon_url
  .actions
    = f.submit 'Save'

app/views/weapons/edit.html.haml
%h1 Editing weapon

= render 'form'

= link_to 'Show', @weapon
\|
= link_to 'Back', weapons_path

app/views/weapons/index.html.haml
%h1 Listing weapons

%table
  %tr
    %th Name
    %th Level
    %th Armor
    %th Hit points
    %th Attack power
    %th Critical damage
    %th Critical chance
    %th Condition damage
    %th Condition duration
    %th Healing power
    %th Boon duration
    %th Magic find
    %th Slot
    %th Gw2db url
    %th Icon url
    %th
    %th
    %th

  - @weapons.each do |weapon|
    %tr
      %td= weapon.name
      %td= weapon.level
      %td= weapon.armor
      %td= weapon.hit_points
      %td= weapon.attack_power
      %td= weapon.critical_damage
      %td= weapon.critical_chance
      %td= weapon.condition_damage
      %td= weapon.condition_duration
      %td= weapon.healing_power
      %td= weapon.boon_duration
      %td= weapon.magic_find
      %td= weapon.slot
      %td= weapon.gw2db_url
      %td= weapon.icon_url
      %td= link_to 'Show', weapon
      %td= link_to 'Edit', edit_weapon_path(weapon)
      %td= link_to 'Destroy', weapon, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Weapon', new_weapon_path

app/views/weapons/new.html.haml
%h1 New weapon

= render 'form'

= link_to 'Back', weapons_path

app/views/weapons/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @weapon.name
%p
  %b Level:
  = @weapon.level
%p
  %b Armor:
  = @weapon.armor
%p
  %b Hit points:
  = @weapon.hit_points
%p
  %b Attack power:
  = @weapon.attack_power
%p
  %b Critical damage:
  = @weapon.critical_damage
%p
  %b Critical chance:
  = @weapon.critical_chance
%p
  %b Condition damage:
  = @weapon.condition_damage
%p
  %b Condition duration:
  = @weapon.condition_duration
%p
  %b Healing power:
  = @weapon.healing_power
%p
  %b Boon duration:
  = @weapon.boon_duration
%p
  %b Magic find:
  = @weapon.magic_find
%p
  %b Slot:
  = @weapon.slot
%p
  %b Gw2db url:
  = @weapon.gw2db_url
%p
  %b Icon url:
  = @weapon.icon_url

= link_to 'Edit', edit_weapon_path(@weapon)
\|
= link_to 'Back', weapons_path