config/routes.rb
Gw2AwesomeBuilder::Application.routes.draw do
  resources :weapons

  resources :jewelries

  resources :suits

  resources :trinkets do
    get 'page/:page', :action => :index, :on => :collection
  end

  resources :outfits do
    get 'page/:page', :action => :index, :on => :collection
  end

  resources :armors do
    get 'page/:page', :action => :index, :on => :collection
  end

  resources :enhancements do
    get 'page/:page', :action => :index, :on => :collection
  end

  resources :statistics do
    get 'page/:page', :action => :index, :on => :collection
  end

  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/enhancement.rb
class Enhancement < ActiveRecord::Base
  resourcify
  attr_accessible :name, :multiplier, :statistic_id

  # Associations
  belongs_to :statistic
  has_many :gear_enhancements

  # Polymorphic Associations
  has_many :armors, through: :gear_enhancements, source: :gear, source_type: 'Armor'
  has_many :trinkets, through: :gear_enhancements, source: :gear, source_type: 'Trinket'

  # Validations
  validates :name,
    presence:true,
    uniqueness: true,
    length: { maximum: 32 }
  validates :multiplier,
    presence: true,
    numericality: { greater_than: 0 }
  validates :statistic_id,
    presence: true
end

app/controllers/enhancements_controller.rb
class EnhancementsController < ApplicationController
  # GET /enhancements
  # GET /enhancements.json
  def index
    @enhancements = Enhancement.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @enhancements }
    end
  end

  # GET /enhancements/1
  # GET /enhancements/1.json
  def show
    @enhancement = Enhancement.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @enhancement }
    end
  end

  # GET /enhancements/new
  # GET /enhancements/new.json
  def new
    @enhancement = Enhancement.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @enhancement }
    end
  end

  # GET /enhancements/1/edit
  def edit
    @enhancement = Enhancement.find(params[:id])
  end

  # POST /enhancements
  # POST /enhancements.json
  def create
    @enhancement = Enhancement.new(params[:enhancement])

    respond_to do |format|
      if @enhancement.save
        format.html { redirect_to @enhancement, notice: 'Enhancement was successfully created.' }
        format.json { render json: @enhancement, status: :created, location: @enhancement }
      else
        format.html { render action: "new" }
        format.json { render json: @enhancement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /enhancements/1
  # PUT /enhancements/1.json
  def update
    @enhancement = Enhancement.find(params[:id])

    respond_to do |format|
      if @enhancement.update_attributes(params[:enhancement])
        format.html { redirect_to @enhancement, notice: 'Enhancement was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @enhancement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enhancements/1
  # DELETE /enhancements/1.json
  def destroy
    @enhancement = Enhancement.find(params[:id])
    @enhancement.destroy

    respond_to do |format|
      format.html { redirect_to enhancements_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/enhancements_helper.rb
module EnhancementsHelper
end

app/views/enhancements/_form.html.haml
= form_for @enhancement do |f|
  - if @enhancement.errors.any?
    #error_explanation
      %h2= "#{pluralize(@enhancement.errors.count, "error")} prohibited this enhancement from being saved:"
      %ul
        - @enhancement.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :statistic
    = f.text_field :statistic
  .field
    = f.label :multiplier
    = f.number_field :multiplier
  .actions
    = f.submit 'Save'

app/views/enhancements/edit.html.haml
%h1 Editing enhancement

= render 'form'

= link_to 'Show', @enhancement
\|
= link_to 'Back', enhancements_path

app/views/enhancements/index.html.haml
%h1 Listing enhancements

%table
  %tr
    %th Name
    %th Statistic
    %th Multiplier
    %th
    %th
    %th

  - @enhancements.each do |enhancement|
    %tr
      %td= enhancement.name
      %td= enhancement.statistic
      %td= enhancement.multiplier
      %td= link_to 'Show', enhancement
      %td= link_to 'Edit', edit_enhancement_path(enhancement)
      %td= link_to 'Destroy', enhancement, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Enhancement', new_enhancement_path

app/views/enhancements/new.html.haml
%h1 New enhancement

= render 'form'

= link_to 'Back', enhancements_path

app/views/enhancements/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @enhancement.name
%p
  %b Statistic:
  = @enhancement.statistic
%p
  %b Multiplier:
  = @enhancement.multiplier

= link_to 'Edit', edit_enhancement_path(@enhancement)
\|
= link_to 'Back', enhancements_path